logLevel: 'info'

processesSettings: 
  common:
    size: 10000
  customFilterSetting:
    common:
      size: 1000
    minValue: 80

chains:
  -
    name: "MyTestChain"
    processes:
      - "CustomEmitter"
      - "CustomFilter"
      - "CustomSender"
  -
    name: "MyAnotherChain"
    processes:
      - "CustomReader"
      - "CustomFilter"
      - "CustomSender"