logLevel: 'info'

processesSettings: 
  size: 10000
  customFilterSetting:
    size: 1
    minValue: 10

chains:
  -
    name: "MyTestChain"
    processes:
      - "CustomEmitter"
      - "CustomFilter"
      - "CustomSender"
  -
    name: "MyAnotherChain"
    processes:
      - "CustomReader"
      - "CustomFilter"
      - "CustomSender"